# Generated by Django 5.0 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.TextField(help_text='The original news headline or article body submitted for verification.', verbose_name='News Text / Headline')),
                ('prediction', models.CharField(choices=[('REAL', 'Real News'), ('FAKE', 'Fake News')], help_text='Classification verdict: REAL or FAKE.', max_length=10, verbose_name='Prediction Verdict')),
                ('confidence', models.FloatField(help_text='Probability confidence percentage calculated by the classifier (50.0 - 99.9%).', verbose_name='Confidence Score (%)')),
                ('prob_real', models.FloatField(default=0.0, verbose_name='Real Probability (%)')),
                ('prob_fake', models.FloatField(default=0.0, verbose_name='Fake Probability (%)')),
                ('sensationalism_score', models.IntegerField(default=0, verbose_name='Sensationalism Score (0-100)')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Submitted By User')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Analysis Timestamp')),
            ],
            options={
                'verbose_name': 'News Prediction',
                'verbose_name_plural': 'News Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_verdict', models.CharField(choices=[('AGREE', 'Agree with Model Verdict'), ('DISAGREE', 'Disagree / Reported as Error')], max_length=15)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='detector.prediction')),
            ],
            options={
                'verbose_name': 'Prediction Feedback',
                'verbose_name_plural': 'Prediction Feedbacks',
            },
        ),
    ]
