# Generated by Django 5.2.17 on 2026-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy_before', models.FloatField()),
                ('accuracy_after', models.FloatField()),
                ('new_vocabulary_count', models.IntegerField(default=0)),
                ('articles_ingested', models.IntegerField(default=1)),
                ('trigger_type', models.CharField(default='auto_stream', max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Active Learning Session',
                'verbose_name_plural': 'Active Learning Sessions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecentNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Article Title / Headline')),
                ('content', models.TextField(verbose_name='Article Body Text')),
                ('source', models.CharField(default='Live Wire', max_length=150, verbose_name='News Source')),
                ('category', models.CharField(default='General', max_length=100, verbose_name='Topic Category')),
                ('suggested_label', models.CharField(choices=[('REAL', 'Real News'), ('FAKE', 'Fake News')], default='REAL', max_length=10)),
                ('verified_label', models.CharField(blank=True, choices=[('REAL', 'Real News'), ('FAKE', 'Fake News')], max_length=10, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_learned', models.BooleanField(default=False, verbose_name='Absorbed into ML Model')),
                ('learned_at', models.DateTimeField(blank=True, null=True, verbose_name='Learning Timestamp')),
                ('extracted_ngrams', models.TextField(blank=True, help_text='Comma-separated salient n-grams extracted from text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recent News Article',
                'verbose_name_plural': 'Recent News Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
